# keymap.toml

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin hide-preview"
desc = "Hide or show preview"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
# glow.yazi
on = "<C-e>"
run = "seek 5"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = "seek -5"

[[mgr.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[mgr.prepend_keymap]]
on  = "k"
run = "plugin arrow -1"

[[mgr.prepend_keymap]]
on  = "j"
run = "plugin arrow 1"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"
