# config.yml
---
api_key: ~
limit: 10
lucky: false
sites:
  - stackoverflow
  - superuser
  - meta
  - webapps
  - gaming
  - cooking
  - gamedev
  - photo
  - diy
  - askubuntu
  - money
  - english
  - ux
  - unix
  - apple
  - softwareengineering
  - electronics
  - android
  - boardgames
  - homebrew
  - security
  - writing
  - video
  - graphicdesign
  - scifi
  - codereview
  - quant
  - fitness
  - music
  - japanese
  - french
  - linguistics
  - hermeneutics
  - history
  - movies
  - psychology
  - outdoors
  - martialarts
  - sports
  - academia
  - workplace
  - chess
  - raspberrypi
  - russian
  - patents
  - robotics
  - politics
  - anime
  - sustainability
  - reverseengineering
  - networkengineering
  - freelancing
  - blender
  - space
  - sound
  - astronomy
  - tor
  - ebooks
  - arduino
  - hinduism
  - emacs
  - lifehacks
  - coffee
  - vi
  - musicfans
  - woodworking
  - law
  - opensource
  - elementaryos
  - computergraphics
  - hardwarerecs
  - softwarerecs
  - 3dprinting
  - languagelearning
  - retrocomputing
  - ai
  - iot
  - literature
  - devops
  - quantumcomputing
  - drones
  - genai
search_engine: stackexchange
